###

# curl --location 'http://127.0.0.1:8000/api/hello'
GET http://127.0.0.1:8000/api/hello

###

# curl --location 'http://127.0.0.1:8000/api/hello' 
#--header 'Authorization: Bearer 8eGnWoZWX29cOk2CEBqWO9qBIP3zQI'
GET http://127.0.0.1:8000/api/hello
Authorization: Bearer 8eGnWoZWX29cOk2CEBqWO9qBIP3zQI

###

